### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку Linked_list Байдин Дмитрий

### ISSUE THREAD

**Issue by baydindima** [baydindima/au-linux-kernel-spring-2016#1]
1b835a0b99f836418570b0bf01ca6e21edd5db91

**Comment by eabatalov** [comment]
80% for the task. See comments in commit.

**Comment by baydindima** [comment]
Забыл обновить ссылку на комит 
https://github.com/baydindima/au-linux-kernel-spring-2016/commit/ba41fbf8c08b4233812ec80bef4d553cf90c17f5

**Comment by eabatalov** [comment]
Ok. 100% for the task with some stylistic problems.
